import json
from pathlib import Path

from teich.trace_readme import build_traces_readme, write_traces_readme


def test_build_traces_readme_includes_model_and_references_tools(tmp_path: Path):
    trace_file = tmp_path / "trace.jsonl"
    trace_file.write_text(
        '{"type":"session_meta","payload":{"id":"session1"}}\n'
        '{"type":"response_item","payload":{"type":"message","role":"user","content":[{"type":"input_text","text":"Build a todo app"}]}}\n'
        '{"type":"response_item","payload":{"type":"tool_schema","name":"bash","schema":{"description":"Run shell commands","parameters":{"type":"object","properties":{"command":{"type":"string"}},"required":["command"],"additionalProperties":false}}}}\n'
        '{"type":"response_item","payload":{"type":"function_call","name":"bash","call_id":"call_1","arguments":"{\\"command\\":\\"ls\\"}"}}\n',
        encoding="utf-8",
    )

    readme = build_traces_readme(
        pretty_name="Agentic Training Traces",
        trace_files=[trace_file],
        tags=["agent-traces", "codex"],
        model_id="codex-mini-latest",
    )

    assert "All assistant responses were generated by **codex-mini-latest**." in readme
    assert "## Training-ready tools" in readme
    assert "tools.json" in readme
    assert '"name": "bash"' not in readme
    assert "## Conversion" in readme
    assert "load_traces" in readme
    assert "format_and_mask" in readme
    assert "convert_traces_to_training_data" in readme


def test_write_traces_readme_creates_tools_json(tmp_path: Path):
    trace_file = tmp_path / "trace.jsonl"
    trace_file.write_text(
        '{"type":"session_meta","payload":{"id":"session1"}}\n'
        '{"type":"response_item","payload":{"type":"tool_schema","name":"bash","schema":{"description":"Run shell commands","parameters":{"type":"object","properties":{"command":{"type":"string"}},"required":["command"],"additionalProperties":false}}}}\n'
        '{"type":"response_item","payload":{"type":"function_call","name":"bash","call_id":"call_1","arguments":"{\\"command\\":\\"ls\\"}"}}\n',
        encoding="utf-8",
    )

    readme_path = write_traces_readme(
        tmp_path,
        pretty_name="Agentic Training Traces",
        tags=["agent-traces"],
        model_id="test-model",
    )

    assert readme_path.exists()
    tools_path = tmp_path / "tools.json"
    assert tools_path.exists()

    tools = json.loads(tools_path.read_text(encoding="utf-8"))
    assert len(tools) == 1
    assert tools[0]["function"]["name"] == "bash"
    assert tools[0]["function"]["description"] == "Run shell commands"
    assert tools[0]["function"]["parameters"]["additionalProperties"] is False
